export type SimulationStatus = 'CREATED' | 'VALIDATING' | 'PREPROCESSING' | 'GENERATING_INPUT' | 'SPH_RUNNING' | 'DELFT3D_RUNNING' | 'POSTPROCESSING' | 'IMPACT_ANALYSIS' | 'EXPORTING' | 'COMPLETED' | 'FAILED';

export interface PipelineStage { stage_id: string; message: string; progress: number; done: boolean; timestamp: string; }
export interface SimulationJobStatus { simulation_id: string; status: SimulationStatus; progress: number; current_stage: string; stages: PipelineStage[]; error?: string; is_mock: boolean; }
export interface FloodResult { model: string; is_mock: boolean; disclaimer: string; max_depth_m: number; avg_depth_m: number; max_velocity_ms: number; inundation_area_km2: number; peak_discharge_m3s: number; arrival_time_hrs: number; output_dir: string; file_paths: Record<string, string>; }
export interface ImpactResult { model: string; is_mock: boolean; is_preliminary: boolean; disclaimer: string; affected_population: number; affected_villages: number; affected_buildings: number; affected_roads_km: number; affected_bridges: number; affected_agriculture_ha: number; affected_infrastructure: number; impact_categories: Record<string, { applicable: boolean; area_fraction?: number; estimated_area_km2?: number }>; flood_area_km2: number; max_depth_m: number; }
export interface ComparisonMetric { sph: number; delft3d: number; difference: number; pct_difference: number; }
export interface ModelComparison { is_mock: boolean; disclaimer: string; metrics: { inundation_area_km2: ComparisonMetric; max_depth_m: ComparisonMetric; avg_depth_m: ComparisonMetric; max_velocity_ms: ComparisonMetric; peak_discharge_m3s: ComparisonMetric; arrival_time_hrs: ComparisonMetric; affected_population: ComparisonMetric; }; }
export interface HydrologyPoint { timestamp: string; hour: number; discharge_m3s: number; water_level_m: number; rainfall_mm_hr: number; velocity_ms: number; stage: string; is_demo: boolean; }
export interface DamInfo { name: string; type: string; coordinates: [number, number]; height_m: number; reservoir_elevation_m: number; reservoir_area_km2: number; reservoir_volume_mcm: number; normal_water_level_m: number; max_water_level_m: number; is_demo: boolean; }
export interface ModelStatus { model_name: string; full_name: string; adapter_status: string; execution_mode: string; is_mock: boolean; real_solver_connected: boolean; disclaimer: string; }
